[custom]
# 基于 ACL4SSR_Online.ini 配置
ruleset=🎯 全球直连,[]DOMAIN-SUFFIX,superacme.com

# 引用原配置
include_remarks=(飞兔|Feitu)
clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online.ini 